### PR TITLE
fix jcasc test harness

### PR DESCRIPTION
**Pull request by casz**

### CODE REVIEW

**Comment by jglick** [comment]
needs merge

**Comment by jvz** [comment]
Is this waiting on anything else before merging?

**Comment by casz** [comment]
there @jvz hopefully once it is green, we are good to go :D

**Comment by jvz** [comment]
Got a strange test failure that may or may not be relevant.

**Comment by casz** [comment]
unrelated it also happened on the other PR

**Comment by jvz** [comment]
Thanks for the PR!

**Comment by jglick** [comment]
@jvz note that we are going to need a release of this: https://github.com/jenkinsci/bom/pull/164#issuecomment-574203377

**Comment by jvz** [comment]
Making one right now.

**Comment by jvz** [comment]
Released as 2.3.1.

**Pull request merged**
