### PR TITLE
Update icon SVG

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed complements https://github.com/jenkinsci/jenkins/pull/6273 and adjust the icon to match with the new "Manage Jenkins" desgin.

Currently the icon looks like 

but with change proposed it turns to 

like other plugins look like

### CODE REVIEW

**Comment by NotMyFault** [comment]
cc @jglick if you don't mind taking a look :)

Even if I've risen this PR from a refactor branch, would be nice to have it released nevertheless I guess, to not have stretched icons in the next weekly release 👀

**Review by timja — APPROVED** [review]

**Comment by daniel-beck** [comment]
Does this mean #230 was wrong?

**Comment by jglick** [comment]
I am not a plugin maintainer.

**Comment by NotMyFault** [comment]
> I am not a plugin maintainer.

My bad, I was going off the RPU and saw you merged a PR recently. Looks like it's sometimes hard to tell who actually maintains projects and who just has permission according to the RPU and/or is listed as team member on GitHub 👀

**Comment by jglick** [comment]
Yes, I did a few things when I needed to but do not intend to generally maintain it.

**Comment by jglick** [comment]
@timja merge after testing I guess.

**Comment by timja** [comment]
> Modernise UI #287

I've checked and it looks fine, although https://github.com/jenkinsci/credentials-plugin/pull/287

**Review by timja — APPROVED** [review]

**Pull request merged**
