### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@reviewbybees any one can help check the changes? tks

**Comment by LinuxSuRen** [comment]
Oh, I see. Just it's been a long time.

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Why nobody review this pr?

**Comment by oleg-nenashev** [comment]
Well, you requested reviewbybees when you are not a CB employee. Use @jenkinsci/code-reviewers when there is no response from the maintainer.

**Comment by LinuxSuRen** [comment]
@oleg-nenashev Thanks for the tip.

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers

**Pull request merged**
