### PR TITLE
[JENKINS-38048] Relax nullability on Item/ItemGroup context parameters

### PR DESCRIPTION
**Pull request by jglick**
Used implicitly by https://github.com/jenkinsci/git-plugin/pull/437 and https://github.com/jenkinsci/subversion-plugin/pull/169.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Can you explain why?

These newly introduced methods take a `@Nonnull` parameter, then do nothing with it except delegate to longstanding methods accepting a `@Nullable` parameter (with an IMO sensible meaning of looking only in global scope).

**Comment by stephenc** [comment]
Well if we allow `null` then we will get people passing `null` and then the `null` needs to be typecast... plus I now believe it was a mistake to allow the previous APIs to accept `null` rather than forcing people to be explicit.

I am open to debate on this subject. Just my initial push-back

**Comment by jglick** [comment]
> forcing people to be explicit

Well instead of

```java
return new StandardListBoxModel()
        .includeEmptyValue()
        .includeMatchingAs(
                project instanceof Queue.Task
                        ? Tasks.getAuthenticationOf((Queue.Task) project)
                        : ACL.SYSTEM,
                project,
                StandardUsernameCredentials.class,
                GitURIRequirementsBuilder.fromUri(url).build(),
                GitClient.CREDENTIALS_MATCHER)
        .includeCurrentValue(credentialsId);
```

you could inline the implementation of `includeMatchingAs` to satisfy the _existing_ nullability signatures:

```java
StandardListBoxModel model = new StandardListBoxModel().includeEmptyValue();
model.addMissing(CredentialsProvider.listCredentials(
    StandardUsernameCredentials.class,
    project,
    project instanceof Queue.Task
        ? Tasks.getAuthenticationOf((Queue.Task) project)
        : ACL.SYSTEM,
    GitURIRequirementsBuilder.fromUri(url).build(),
    GitClient.CREDENTIALS_MATCHER)));
return model.includeCurrentValue(credentialsId);
```

and then to satisfy proposed _stricter_ nullability you would have to say

```java
StandardListBoxModel model = new StandardListBoxModel().includeEmptyValue();
Authentication authentication = project instanceof Queue.Task
        ? Tasks.getAuthenticationOf((Queue.Task) project)
        : ACL.SYSTEM;
List<DomainRequirement> domainRequirements = GitURIRequirementsBuilder.fromUri(url).build();
CredentialsMatcher matcher = GitClient.CREDENTIALS_MATCHER);
model.addMissing(project != null ?
    CredentialsProvider.listCredentials(
        StandardUsernameCredentials.class,
        project,
        authentication,
        domainRequirements,
        matcher) :
    CredentialsProvider.listCredentials(
        StandardUsernameCredentials.class,
        Jenkins.getInstance(),
        authentication,
        domainRequirements,
        matcher));
return model.includeCurrentValue(credentialsId);
```

which does not feel like an improvement to me, much as I also like explicit APIs.

**Comment by stephenc** [comment]
Compromise suggestion... make the `ItemGroup` variants can be `@Nullable` the `Item` cannot... I am open to vice-versa if you feel that makes more sense...

**Comment by jglick** [comment]
> make the `ItemGroup` variants can be `@Nullable` the `Item` cannot

Well the motivating case (as shown above) involves a null `Item`.

> I am open to vice-versa

Why would it make sense to allow null in some calls but not others? That sort of inconsistency is the whole point of this PR.

**Comment by jglick** [comment]
Conclusion with @stephenc:

* for the short term, let `Item` overloads be `@Nullable`, but `ItemGroup` overloads remains `@Nonnull`
* file an issue to provide a better system:
   * new methods (not overloads) taking `@Nonnull ModelObject`
   * for non-`Item`/`ItemGroup`, currently just fall back to `Jenkins`, but later could handle `User`, `Node`, etc.
   * introduce a helper method for `Authentication` based on item with possible defaults:
```java
project instanceof Queue.Task ? Tasks.getAuthenticationOf((Queue.Task) project): ACL.SYSTEM
```

**Comment by jglick** [comment]
Made the requested short-term change and filed [JENKINS-39324](https://issues.jenkins-ci.org/browse/JENKINS-39324) for the rest.

**Pull request merged**
