### PR TITLE
Update 'Add credentials' dropdown button

### PR DESCRIPTION
**Pull request by janfaracik**
This PR updates the 'Add credentials' button to use the `.jenkins-button` class as well as to use the [Dropdown component](https://weekly.ci.jenkins.io/design-library/Dropdowns/) over the legacy YUI dropdown.

**Before**
image

**After**
image

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jtnord** [comment]
Has compatability with the ATH been checked with this? The code change otherwise looks reasonable to me.

**Review by basil — APPROVED** [review]
Tested in:

- https://github.com/jenkinsci/acceptance-test-harness/pull/1752
- https://github.com/jenkinsci/bom/pull/3658

**Comment by basil** [comment]
@janfaracik This results in 36 new ATH failures in https://github.com/jenkinsci/acceptance-test-harness/pull/1752. Can you prepare an ATH PR that adapts to this change?

**Comment by janfaracik** [comment]
> @janfaracik This results in 36 new ATH failures in [jenkinsci/acceptance-test-harness#1752](https://github.com/jenkinsci/acceptance-test-harness/pull/1752). Can you prepare an ATH PR that adapts to this change?

Thanks Basil! I will do :)

**Comment by janfaracik** [comment]
@basil Heya, when updating ATH tests for plugin changes, do we need to maintain compatibility with the old version of the plugin?

**Comment by timja** [comment]
> @basil Heya, when updating ATH tests for plugin changes, do we need to maintain compatibility with the old version of the plugin?

FWIW I know Basil asked you to maintain forward compatibility it depends on whether the plugin baseline is supported on the latest LTS version really.

If the change will be released and it will work on latest weekly and latest LTS then you don't really need forward compatibility as we only support the latest version of the plugin in ATH, but if its easy to maintain the compatibility then it makes it so you can merge the ATH change independently which is a good thing

**Pull request merged**
