### PR TITLE
[FIXED JENKINS-30326] Need to provide a mechanism to search the crede…

### PR DESCRIPTION
**Pull request by stephenc**
…ntials of ACL.SYSTEM also

@reviewbybees esp @jtnord

### CODE REVIEW

**Comment by jtnord** [comment]
:bee:

**Comment by amuniz** [comment]
:bee:

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
Smells like a code dup btw

**Comment by jglick** [comment]
Belated :-1: for lack of a test for this far-from-obvious change, but I will ask @jtnord to write an integration test proving that the originally requested use case is in fact fixed with this release.

**Pull request merged**
