### PR TITLE
Credentials action should be hidden only for the root Jenkins, not for folders or users

### PR DESCRIPTION
**Pull request by Vlatombe**
Fix regression from #150, amends #154 

/cc @timja

### CODE REVIEW

**Comment by Vlatombe** [comment]
Not sure what is going on at the CI level though...

**Comment by timja** [comment]
> Not sure what is going on at the CI level though...

that read time out is a flake I've seen before, I retriggered when I approved it =/

**Comment by Vlatombe** [comment]
also /cc @jvz

**Comment by timja** [comment]
Not sure what's going on, re-triggered it a few times, and ran the tests locally on java 11 (all pass).

**Pull request merged**
