### PR TITLE
[JENKINS-20139] Add support to track where a credential is used

### PR DESCRIPTION
**Pull request by stephenc**
[JENKINS-20139](https://issues.jenkins-ci.org/browse/JENKINS-20139)

- Needs to wait for https://github.com/jenkinsci/credentials-plugin/pull/57 to be merged before we can call this done (see TODO task in code)

### CODE REVIEW

**Comment by stephenc** [comment]
screen shot 2016-06-14 at 15 32 19

**Comment by halkeye** [comment]
Peeking at the code, is this something that plugin developers will have to add? 
`CredentialsProvider.trackUsage(build, lookupCredentials(StandardCredentials.class, build));`

**Comment by stephenc** [comment]
Not quite, when a plugin developer retrieves a credential for actual **use** (distinct from pre-validation, probing, etc) they will need to call one of the track methods (or do their own facets if doing something more fancy)

I have no way of distinguishing generic retrieval from usage, hence that necessity. Hopefully I can update the wiki with recommended integration patterns before I get pulled away again

**Comment by stephenc** [comment]
`CredentialsProvider.trackUsage(build, credential)` is the intended usage. Credential parameters are different as they do not normally actually retrieve the credential, rather just the credential ID which is why I need to look it up for tracking.

**Pull request merged**
