### PR TITLE
Replace Prototype.js with native JavaScript

### PR DESCRIPTION
**Pull request by basil**
See [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906). Jenkins core currently uses [Prototype 1.7](https://github.com/prototypejs/prototype/releases/tag/1.7), released on November 15, 2010. The latest version is [Prototype 1.7.3](https://github.com/prototypejs/prototype/releases/tag/1.7.3), released on September 22, 2015. When an attempt was made to upgrade to 1.7.3 in 2018 in [JENKINS-49319](https://issues.jenkins.io/browse/JENKINS-49319), the change had to be reverted. Since this library has been unmaintained for the past 8 years, this PR removes any usages of it in favor of native JavaScript APIs. To test this, I added a new credential from a Freestyle project and verified that the iframe loaded successfully and was refreshed with the new credential after the credential had been created.

### CODE REVIEW

**Comment by basil** [comment]
Note that the maintainers appear to be cherry-picking PRs, as #444 was merged and released before this PR despite this PR being filed first.

**Comment by timja** [comment]
cc @car-roll / @jenkinsci/credentials-plugin-developers  possible to review this?

**Comment by timja** [comment]
cc @jenkinsci/credentials-plugin-developers ?

**Comment by jglick** [comment]
> We are planning to review all the prototype.js PRs at the same time.

I guess that did not happen.

**Review by jglick — APPROVED** [review]
Not really qualified to review these, but looks fine.

**Pull request merged**
