### PR TITLE
Add support for future Manage Jenkins layout

### PR DESCRIPTION
**Pull request by daniel-beck**
Downstream from https://github.com/jenkinsci/jenkins/pull/4546

### CODE REVIEW

**Comment by daniel-beck** [comment]
That… seems a bit premature.

**Comment by jvz** [comment]
It's harmless code, and I haven't released it yet. :)

**Comment by daniel-beck** [comment]
@jvz Could you adapt this plugin to the changed upstream code?

**Comment by jvz** [comment]
> @jvz Could you adapt this plugin to the changed upstream code?

Now it's strongly typed? How can I support that without requiring a recent Jenkins version?

**Comment by daniel-beck** [comment]
@jvz Rename to `getCategoryName`, which is still a string and remains for compatibility.

**Comment by jvz** [comment]
See #140

**Pull request merged**
